
export const baseApi = 'https://pay.asadalpay.com/api/bids/create-bid-finance';
export const apiKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJsZWdhbF9lbnRpdHlfaWQiOjExLCJjcmVhdGVkX2F0IjoiMjAyMy0wNy0xNCAwOToxNjoxOC40MTA0OTQiLCJwYXNzd29yZCI6IjhiMjRiNDM3LWQzNzQtNGFlMS1hOGFlLTFkNjA4ZDEwM2NkYSJ9.5FjjmH7q1On8AdtiOnirzBl347wspBumOYzwDNcyun4"